name: 'Bikeclub Default content'
description: 'Provides sample data for menus, nodes, and users.'
type: 'Content'
recipes:
  - bikeclub_page
config:
  # Strict false applies to config folder, positions taxonomy is created if it does not exist.
  strict: false
